const data = [
  {
    hiddenMessage : "Merci satan pour la caféine",
    title : "Vikings",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kF7TkNOil6oihykSEaMoK80iZ31.jpg",
    description : "Les exploits d'un groupe de vikings de la fin du 8ème siècle jusqu'au milieu du 11ème, mené par Ragnar Lodbrok, l'un des plus populaires héros viking de tous les temps, qui a régné quelques temps sur le Danemark et la Suède...",
    date : 2013,
    nbSeasons : 6,
    nbEpisodes : [9,10,10,20,20,20],
    isFollowed : false,
    lastSeen : [0, 0],
  },
  {
    title : "Vampire Diaries ",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xKltipwfXRgvyD2u79FUnXAZ09F.jpg",
    description : "Quatre mois après le tragique accident de voiture qui a tué leurs parents, Elena Gilbert, 17 ans, et son frère Jeremy, 15 ans, essaient encore de s'adapter à cette nouvelle réalité. Belle et populaire, l'adolescente poursuit ses études au Mystic Falls High en s'efforçant de masquer son chagrin. Elena est immédiatement fascinée par Stefan et Damon Salvatore, deux frères que tout oppose. Elle ne tarde pas à découvrir qu'ils sont en fait des vampires...",
    date : 2009,
    nbSeasons : 8,
    nbEpisodes : [22,22,22,23,22,22,22,16],
    isFollowed : false,
    lastSeen : [0, 0],
  },
  {
    title : "Shōgun",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
    description : "En l'an 1600 au Japon, le seigneur Yoshii Toranaga lutte pour sa survie alors que ses ennemis du Conseil des régents se liguent contre lui, lorsqu'un mystérieux navire européen est retrouvé échoué dans un village de pêcheurs voisin.",
    date : 2024,
    nbSeasons : 1,
    nbEpisodes : [10],
    isFollowed : false,
    lastSeen : [0, 0],
  },
  {
    title : "Small Axe ",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/hI9SLdaMK3tENQTNYnyCCsIx0Wi.jpg",
    description : "L'histoire débute dans les années 1960 et raconte des histoires de la communauté antillaise de Londres, confrontée à un environnement souvent hostile.",
    date : 2020,
    nbSeasons : 1,
    nbEpisodes : [5],
    isFollowed : true,
    lastSeen : [1, 0],
  },
  {
    title : "Hasbin Hôtel",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rXojaQcxVUubPLSrFV8PD4xdjrs.jpg",
    description : "Charlie Morningstar, la Princesse de l'Enfer, lutte pour convaincre les démons et les anges que n'importe quelle âme peut être rachetée. Venez chanter devant cette comédie musicale animée pour adultes sur la rédemption.",
    date : 2024,
    nbSeasons : 1,
    nbEpisodes : [8],
    isFollowed : true,
    lastSeen : [1, 0],
  },
  {
    title : "The Last of us",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/eIQqqWFBtzKFfcxuuemtRNtoIkN.jpg",
    description : "Vingt ans après la destruction de la civilisation moderne, Joel, un survivant endurci, est engagé pour faire sortir Ellie, une jeune fille de 14 ans, d'une zone de quarantaine oppressante. Ce qui n'est au départ qu'un petit travail se transforme rapidement en un voyage brutal et époustouflant, alors que ce duo improbable dépend de l'autre pour sa survie.",
    date : 2023,
    nbSeasons : 1,
    nbEpisodes : [9],
    isFollowed : true,
    lastSeen : [1, 0],
  },
  {
    title : "The Witcher",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rhErSlk0M236rNFertVAZa9lz9S.jpg",
    description : "Le sorcier Geralt, un chasseur de monstres mutant, se bat pour trouver sa place dans un monde où les humains se révèlent souvent plus vicieux que les bêtes.",
    date : 2019,
    nbSeasons : 3,
    nbEpisodes : [8, 8, 8],
    lastSeen : [2,8],
    isFollowed : true,
  },
  {
    title : "Big Mouth",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xLlc3pd0EuX6x6aNPL5mZrkjRXb.jpg",
    description : "Délices et horreurs de la puberté chahutent un groupe d'ados dans cette comédie décapante créée par deux copains de longue date, Nick Kroll et Andrew Goldberg.",
    date : 2017,
    nbSeasons : 7,
    nbEpisodes : [10, 10, 11, 10, 10, 10, 10],
    lastSeen : [6, 10],
    isFollowed : true,
  },
  {
    title : "Fallout",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/AnsSKR9LuK0T9bAOcPVA3PUvyWj.jpg",
    description : "Tirée de l'un des plus grands jeux vidéo de tous les temps, Fallout est une histoire d'inégalités dans un monde où tous sont égaux face au chaos. Deux cents ans après l'apocalypse, les pacifiques habitants de luxueux abris antiatomiques sont contraints de retourner dans le monde incroyablement complexe, joyeusement étrange et extrêmement violent qui les attend à la surface.",
    date : 2024,
    nbSeasons : 1,
    nbEpisodes : [8],
    isFollowed : false,
    lastSeen : [0, 0],
  },
  {
    title : "Alice in Borderland",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/217V9dhelgjELLZGawTmRJ0NNb7.jpg",
    description : "Un gamer paumé et ses deux amis se retrouvent dans un Tokyo parallèle, où ils sont contraints de participer à une série de jeux sadiques pour survivre.",
    date : 2020,
    nbSeasons : 2,
    nbEpisodes : [8,8],
    isFollowed : true,
    lastSeen : [2,8],
  },
  {
    title : "Docteur Who",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xCFZRY658A3Nt0p3uUZUkpeRxPF.jpg",
    description : "Dernier représentant des Seigneurs du temps et âgé de plus de 900 ans, Le Docteur parcourt l'espace et le temps dans son TARDIS. Amoureux de la race humaine, il se fait régulièrement accompagner par une femme ou un homme. Partagé entre folie et génie, insouciant mais conscient de ses responsabilités, il défendra l'humanité quel que soit le prix à payer.",
    date : 2005,
    nbSeasons : 14,
    nbEpisodes : [13,13,13,13,13,13,13,12,12,12,10,10,6],
    isFollowed : true,
    lastSeen : [4, 17],
  },
  {
    title : "Les Anneaux de pouvoir",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gpHezxjqAnZ21o8T9vSSrUKygQ3.jpg",
    description : "Divers personnages, connus et inconnus, doivent faire face à la résurgence du mal en Terre du Milieu. Des profondeurs des Montagnes de Brume aux forêts majestueuses du Lindon, de l'île des Rois de Númenor aux contrées les plus éloignées du monde, ces royaumes et personnages vont forger un héritage qui demeurera bien après leur disparition.",
    date : 2022,
    nbSeasons : 1,
    nbEpisodes : [8],
    isFollowed : true,
    lastSeen : [1, 8],
  },
  {
    title : "NCIS Enquêtes spéciales",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/2exOHePjOTquUsbThPGhuEjYTyA.jpg",
    description : "À la tête de cette équipe du NCIS, qui opère en dehors de la chaîne de commandement militaire, l'agent Special Leroy Jethro Gibbs, un enquêteur qualifié dont les qualités sont d'être intelligent, solide et prêt à contourner les règles pour faire le travail. Travaillant sous les ordres de Gibbs, on retrouve l'agent Anthony DiNozzo, l'agent Abby Sciuto et le Dr Donald 'Ducky' Mallard. De meurtre en espionnage anti-terrorisme et sous-marins volés, ces agents spéciaux parcourent la planète pour enquêter sur tous les crimes ayant un lien avec l'US Navy ou l'US Marine Corps.",
    date : 2003,
    nbSeasons : 21,
    nbEpisodes : [23,23,24,24,19,25,24,24,24,24,24,24,24,24,24,24,20,16,21,22,10],
    isFollowed : true,
    lastSeen : [15, 1],
  },
  {
    title : "Grey's Anatomy ",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/jcEl8SISNfGdlQFwLzeEtsjDvpw.jpg",
    description : "Meredith Grey, fille d'un chirurgien très réputé, commence son internat de première année en médecine chirurgicale dans un hôpital de Seattle. La jeune femme s'efforce de maintenir de bonnes relations avec ses camarades internes, mais dans ce métier difficile la compétition fait rage.",
    date : 2005,
    nbSeasons : 20,
    nbEpisodes : [9,27,25,17,24,24,22,24,24,24,24,24,24,24,25,21,17,20,20,10],
    isFollowed : false,
    lastSeen : [0,0],
  },
  {
    title : "Only Murders in the Building",
    img : "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dEPEwV74c04cF2px4rVFdrD0kMc.jpg",
    description : "À la tête de cette équipe du NCIS, qui opère en dehors de la chaîne de commandement militaire, l'agent Special Leroy Jethro Gibbs, un enquêteur qualifié dont les qualités sont d'être intelligent, solide et prêt à contourner les règles pour faire le travail. Travaillant sous les ordres de Gibbs, on retrouve l'agent Anthony DiNozzo, l'agent Abby Sciuto et le Dr Donald 'Ducky' Mallard. De meurtre en espionnage anti-terrorisme et sous-marins volés, ces agents spéciaux parcourent la planète pour enquêter sur tous les crimes ayant un lien avec l'US Navy ou l'US Marine Corps.",
    date : 2021,
    nbSeasons : 3,
    nbEpisodes : [10,10,10],
    isFollowed : true,
    lastSeen : [3, 10],
  },
]

export default data;
